#!/bin/sh

# Script posted in the following forum:
# 	https://bbs.archlinux.org/viewtopic.php?id=147773


# turn on HDMI 
tvservice --preferred > /dev/null

# set frame buffer; refresh
fbset -depth 8; fbset -depth 16; xrefresh
